### ISSUE TITLE
Add StableSwap math

### ISSUE THREAD

**Issue by dexterslabor** [galacticcouncil/HydraDX-wasm#11]
Please add [calculate_out_given_in](https://github.com/galacticcouncil/Basilisk-node/blob/feat/stableswap/pallets/stablewap/src/math.rs#L93-L103) and [calculate_in_given_out](https://github.com/galacticcouncil/Basilisk-node/blob/feat/stableswap/pallets/stablewap/src/math.rs#L105-L115) from the StableSwap/curve math.

**Comment by enthusiastmartin** [comment]
Companion [HydraDX-math](https://github.com/galacticcouncil/HydraDX-math/issues/34)

**Comment by enthusiastmartin** [comment]
API added. Returns 0 now.

**Comment by enthusiastmartin** [comment]
Stableswap math  was added. Currently works for 2 assets only. 

It is no longer relevant as stableswap supports now multi assets pool. it will need update in future.
